### ISSUE TITLE
Not seeing 2018 statewide candidates for offices like governor in the processed data files

### ISSUE THREAD

**Issue by palewire** [california-civic-data-coalition/django-calaccess-processed-data#190]

**Comment by gordonje** [comment]
Future assembly and senate candidacies are there, but not the executive offices. The executive office contests are not even in the CandidateContest database table.

Here's one part of the problem, if not the whole thing: The `.office_name` property on the `Form501Filing` concatenates the candidate's office type and district (e.g. `'Assembly 40'`) to create a full label used for getting or creating the OCD `Post`. District is a numeric field on the model and is NULL for executive branch office candidates. This resulted in `.office_name` values like `'Governor None'`.

**Comment by gordonje** [comment]
The above fix uncovered an additional issue in the merge function (see f23c889422478a42f0d81aac2400c0e5ce56ee81), which is now also fixed.

Now the executive branch candidates are appearing in the published csv files.

**Comment by palewire** [comment]
Using this GIF not just because it's appropriate, but also for @aboutaaron. 

![giphy-downsized-large](https://user-images.githubusercontent.com/9993/32202800-5b8d317a-bd9c-11e7-8173-5d844818d42d.gif)
