### ISSUE TITLE
Scraped candidates without scraped IDs

### ISSUE THREAD

**Issue by gordonje** [california-civic-data-coalition/django-calaccess-processed-data#28]
On the [Candidates & Elected Officials page](http://cal-access.ss.ca.gov/Campaign/Candidates/) in CAL-ACCESS, some names are not hyperlinked and, thus, are collected without a scraped ID. We're talking roughly 40 percent of the collected candidates (about 2,400 records).

Can we figure out what's going on with these?

**Comment by gordonje** [comment]
One example is KEVIN D MELTON who ran for assembly seat #78 in the 2016 primary and general elections.

Querying the `FILERS_CD` table like so:
```sql
SELECT *
FROM "FILERNAME_CD"
WHERE UPPER("NAML") || UPPER("NAMF") LIKE '%MELTON%KEVIN%';
```

There are five records that seem to map to this guy:
```txt
FILER_ID  XREF_FILER_ID  NAML    NAMF     FILER_TYPE                     STATUS  EFFECT_DT   ADR1                           
--------  -------------  ------  -------  -----------------------------  ------  ----------  -----------------------------  
1382941   1382941        MELTON  KEVIN    TREASURER/RESPONSIBLE OFFICER  ACTIVE  2016-02-16  4876 SANTA MONICA AVE #148     
1382943   1382943        MELTON  KEVIN    CANDIDATE/OFFICEHOLDER         ACTIVE  2016-02-16  4876 SANTA MONICA AVE #148     
1358738   1358738        MELTON  KEVIN D  CANDIDATE/OFFICEHOLDER         ACTIVE  2015-04-27  4876 SANTA MONICA AVENUE #148  
1358738   1358738        MELTON  KEVIN D  CANDIDATE/OFFICEHOLDER         ACTIVE  2015-04-27  4876 SANTA MONICA AVENUE #148  
1358738   1358738        MELTON  KEVIN D  CANDIDATE/OFFICEHOLDER         ACTIVE  2015-04-27  4876 SANTA MONICA AVENUE #148  
```

No errors when passing any one of these `FILER_ID` values into the query string for Campaign/Committees/Detail.aspx:

* http://cal-access.ss.ca.gov/Campaign/Committees/Detail.aspx?id=1382941&session=2015&view=general
* http://cal-access.ss.ca.gov/Campaign/Committees/Detail.aspx?id=1382943&session=2015&view=general
* http://cal-access.ss.ca.gov/Campaign/Committees/Detail.aspx?id=1358738&session=2015&view=general

These web pages all include the message: 

> This committee has not electronically filed a Form 460/461/450 for this election cycle. For further information, click on prior sessions to see if historical filings are available. Also check for late contribution filings if a major filing deadline has not yet occurred for this election cycle.

Our derived `calaccess_processed_candidatecommittee` table only has one mapping between one of these candidate filer_ids and a committee filer_id:
```
id     candidate_filer_id  committee_filer_id  link_type_id  link_type_description              first_session  last_session  first_effective_date  last_effective_date  first_termination_date  last_termination_date  
-----  ------------------  ------------------  ------------  ---------------------------------  -------------  ------------  --------------------  -------------------  ----------------------  ---------------------  
24253  1358738             1382942             12011         CANDIDATE CONTROLS THIS COMMITTEE  2015           2015          2016-02-16            2016-02-16           (null)                  (null)                 
```
I also checked the `FILER_LINKS_CD` table from which we derive the above records. This appears to be the only candidate-to-committee mapping.

Here's where it starts to get a little weird: There actually are four Form 460 filings from this committee in 2016:
```
id       FILER_ID  FILING_ID  PERIOD_ID  FORM_ID  FILING_SEQUENCE  FILING_DATE  STMNT_TYPE  STMNT_STATUS  SESSION_ID  USER_ID    SPECIAL_AUDIT  FINE_AUDIT  RPT_START   RPT_END     RPT_DATE  FILING_TYPE  
-------  --------  ---------  ---------  -------  ---------------  -----------  ----------  ------------  ----------  ---------  -------------  ----------  ----------  ----------  --------  -----------  
1930059  1382942   2090713    (null)     F460     0                2016-10-07   10005       11003         2015        MPACHECO   11003          11003       2016-07-01  2016-09-24  (null)    (null)       
1902735  1382942   2072025    (null)     F460     0                2016-07-18   10005       11001         2015        MDIGRAZIA  11003          11001       2016-05-22  2016-06-30  (null)    (null)       
1884296  1382942   2052405    (null)     F460     0                2016-06-06   10005       11001         2015        MDIGRAZIA  11003          11001       2016-04-24  2016-05-21  (null)    (null)       
1867511  1382942   2045078    (null)     F460     0                2016-05-11   10005       11001         2015        MDIGRAZIA  11003          11001       2016-01-01  2016-04-23  (null)    (null)       
```

But there aren't any records with these filing_ids in `CVR_CAMPAIGN_DISCLOSURE_CD`, `RCPT_CD` or `EXPN_CD` 

```sql
SELECT 'CVR_CAMPAIGN_DISCLOSURE_CD' AS tablename, COUNT(*) AS the_count
FROM "CVR_CAMPAIGN_DISCLOSURE_CD"
WHERE "FILING_ID" IN (
    2090713,
    2072025,
    2052405,
    2045078
)
UNION
SELECT 'RCPT_CD' AS tablename, COUNT(*) AS the_count
FROM "RCPT_CD"
WHERE "FILING_ID" IN (
    2090713,
    2072025,
    2052405,
    2045078
)
UNION
SELECT 'EXPN_CD' AS tablename, COUNT(*) AS the_count
FROM "EXPN_CD"
WHERE "FILING_ID" IN (
    2090713,
    2072025,
    2052405,
    2045078
);
```

Which may be why they are suppressed by the website? Or are these being exclude because of some particular value in some particular column (I looked at `FILER_FILINGS_CD.STMNT_STATUS`, but it is not that.

But at least our derived processed models are consistent with the website in excluding these filings. Might be worth looking at other examples of scraped candidates who did not have hyperlinks.

**Comment by gordonje** [comment]
Couple of more observations...

Pass the any of these Form 460 filing_ids into the query string for the CAL-ACCESS pdfgen tool, and you get a CGI error:
* http://cal-access.ss.ca.gov/PDFGen/pdfgen.prg?filingid=2090713&amendid=0
* http://cal-access.ss.ca.gov/PDFGen/pdfgen.prg?filingid=2072025&amendid=0
* http://cal-access.ss.ca.gov/PDFGen/pdfgen.prg?filingid=2052405&amendid=0
* http://cal-access.ss.ca.gov/PDFGen/pdfgen.prg?filingid=2045078&amendid=0

Also, if you look these filing_ids up in the [`FILINGS_CD`](http://calaccess.californiacivicdata.org/documentation/calaccess-files/filings-cd/) table, all of them have `FILING_TYPE` value of 22005, which maps to something called "AMS".  According to the [CAL-ACCESS overview](http://www.documentcloud.org/documents/2711624-Overview.html#document/p2) this stands for Agency Management Subsystems. Based on the workflow outlined in the diagram, I suspect this data was keyed in manually by staff members of the Secretary of State, Political Reform Division.

**Comment by gordonje** [comment]
The bottom line question, which we seem incapable of answering on our own, is "How much money did Kevin Melton raise and spend while running for the state assembly in 2016?"

According the [FPPC's current manual](http://www.fppc.ca.gov/content/dam/fppc/NS-Documents/TAD/Campaign%20Manuals/Manual_1/Manual-1-Chapter-10-When-to-File-Form-460.pdf), candidates are supposed to file semi-annual campaign statements regardless of whether or not they raise or spend money. 

So what exactly happened here? These are the only scenarios we can imagine:
1. Melton for State Assembly 2016 failed to honor this rule, though it seems like they made an attempt?
2. Melton for State Assembly 2016 did it's part, but the CAL-ACCESS system failed to retain their data.

**Comment by palewire** [comment]
While we do not know why the SoS does not publish an ID on the website, we have fixed this issue on our backend by reconciling the scrape with Form 501s and other CAL-ACCESS tables.
