### ISSUE TITLE
Load OCD Election model

### ISSUE THREAD

**Issue by gordonje** [california-civic-data-coalition/django-calaccess-processed-data#35]
I propose a custom `.load()` method on `ElectionManager` that will query `CandidateScrapedElection` and call `Election.create()`. This is a custom create method that I ripped from another OCD Django model, so it might need some additional tinkering.

**Comment by gordonje** [comment]
Almost forgot about `PropositionScrapedElection` as well.

So maybe then, there will be some conditional logic to create or update the `Election` objects.

**Comment by sahilchinoy** [comment]
What should we do about the fact that the `CandidateScrapedElection` models don't have a date, only a year? Can we add a null option to the `start_time` field?

**Comment by gordonje** [comment]
The proposed spec suggests that `Election` inherit from `Event`, which does not allow nulls in `start_time`. Even though we're just doing our own implementation of that spec right now, I think we should avoid that sort of deviation. I also think CCDC users would find it helpful to have those election dates. 

I previously filled in any missing dates, which are currently hard-coded in the old election loading [.sql file](https://github.com/california-civic-data-coalition/django-calaccess-processed-data/blob/master/calaccess_processed/sql/load_election_model.sql). Some or all of these might need to be moved over to this new load method on `ElectionManager`. I'll keep working on this part.
