### ISSUE TITLE
Load OCD Person and Candidacy models

### ISSUE THREAD

**Issue by gordonje** [california-civic-data-coalition/django-calaccess-processed-data#38]
Should go along with #37.

All the data we need should already be loaded into `ScrapedCandidate`. Maybe this would be a `.load()` method on a custom `CandidacyManager`. 

We can load `Candidacy` without having to load `Person`. But if we do load `Person`, it would probably be easier to load it together with `Candidacy` via Django instead of doing them separately and/or via raw sql (maybe).

**Comment by sahilchinoy** [comment]
When we loop through `ScrapedCandidate`, here's the order of objects we should get or create:
- Division (either statewide or district)
- Election
- Post (we'll need to fill in Senator, Assemblyperson as required)
- CandidateContest
- CandidateSelection
- Person
- Candidacy

We should probably do this in one fell swoop. Maybe as part of a `load_raw_data` method on a `CandidacyManager`?

**Comment by gordonje** [comment]
I was sorta thinking we could load `Division`, `Election`, `Organization` and `Post` separately and before any of the others, which can probably happen in the same `load_raw_data()` method as suggested. 

You can create all the divisions like so
```py
from calaccess_processed.models.opencivicdata.division import Division
Division.objects.load(state='ca')
```

What do you think about something like a custom `get_or_create()` method on a `PersonManager`? If we're going to do that sort of matching, probably the most conservative thing would be to use the scraped_id as a unique person ID. Don't think there's any question at this point that it is the equivalent of the CAL-ACCESS filer_id, right?

This would allow us at least to load the `Candidacy` and `Person` models simultaneously. Maybe `Post` and some of the other models would also want this sort of `.get_or_create()` method.
