### ISSUE TITLE
Load OCD BallotMeasureContest and BallotSelection models

### ISSUE THREAD

**Issue by gordonje** [california-civic-data-coalition/django-calaccess-processed-data#40]
Load from `ScrapedProposition`. Probably another `.load()` method on a custom `BallotMeasureContest`.

**Comment by gordonje** [comment]
Loading `RetentionContest` (i.e., the recall elections, probably goes along with this as well).

**Comment by sahilchinoy** [comment]
I've started this as a `load_raw_data` method in a custom manager. Any advantage to moving it to a `load` method on the model itself?

**Comment by sahilchinoy** [comment]
Also, do we have enough information to fill in `BallotMeasureSelection`? Presumably, the answers are just `Yes` and `No` unless we're dealing with a recall question, but we're not scraping that information from anywhere and I don't see a reason to add it in, since it's not referenced anywhere else.

**Comment by gordonje** [comment]
@sahilchinoy I think you are right.`load_raw_data()` is what it is called on the `ProcessedDataManager`, which is the one the executes the non-scraped model's raw sql file. Having only one name for the method available on each model to load its data (either scraped or derived from the raw tables) is probably the way to go.

**Comment by gordonje** [comment]
With respect to the `BallotMeasureSelection`: It is sort of a silly exercise right now. Would be more necessary if we were modeling election results (i.e., vote counts for the selections).

Still @palewire and I were discussing on the call today, and feel like we should proceed with it. Two things we get out of it are 1) We can use some actual CAL-ACCESS data in our sample json (or whatever) we'll be appending to our OCDEP; and 2) There's been some discussion in hashing out both the elections and campaign finance OCDEPs about linking independent committees to the candidates/measure though support/oppose via ballot selection id. That's second one is a little speculative, but we'll need the ballot selection eventually anyway.
