### ISSUE TITLE
Should Schedule 497 be called Form 497?

### ISSUE THREAD

**Issue by palewire** [california-civic-data-coalition/django-calaccess-processed-data#57]
That's what we call it here http://calaccess.californiacivicdata.org/documentation/calaccess-forms/f497/

**Comment by gordonje** [comment]
Yeah, Schedule 497 seems to be its more colloquial name, maybe that's what it used to be more commonly called, as indicated by the raw table name: `S497_CD`. Same deal with 496 and 498.

However, the official docs refer to these as "forms", not "schedules". For example [FPPC](http://www.fppc.ca.gov/forms.html) and the [.CAL Format 2.01](https://www.documentcloud.org/documents/2712034-Cal-Format-201.html#document/p54). Just looked back at Jim Miller's sample files, and these are prefixed as Form497 as well.

I'll rename it to Form497 in the processed-data app.
