### ISSUE TITLE
Extract itemized and unitemized contributions and expenditure totals from 460 filings

### ISSUE THREAD

**Issue by palewire** [california-civic-data-coalition/django-calaccess-processed-data#61]
This is a common proxy for "small" versus "large" donors and is a value that we will want to make available to analysts. It is not currently on our filing summary process table.

I suspect this is because those values are not found on the cover sheet, but instead on the top sheet in each stack of schedule A and schedule C attachments. 

If that's right, we'll need to decide if we want to take them on the flat cover sheet table, or instead create a new schedule summary model in addition to all the other models we currently have.

**Comment by palewire** [comment]
After inspecting the ``SMRY_CD`` table, I believe I have found the location of these values. 

A SQL query that will return the three Schedule summary lines for a particular filing look like this:

```sql
SELECT "LINE_ITEM", "AMOUNT_A"
FROM "SMRY_CD"
WHERE "FILING_ID" = 2129337
AND "AMEND_ID" = 0
AND "FORM_TYPE" = 'A'
```

That will return something like this:

```
"1";1900556.16
"2";5956.43
"3";1906512.59
```

The first line item is labeled "Amount received this period of $100 or more." This is typically referred to as the itemized or "large donors" and should match the sum of all the contributions disclosed in the receipts table.

The second line item is labeled "Amount received this period - unitemized contributions of less than $100." This is typically referred to as unitemized or "small donors" and none of the money included in its total should appear in the receipts table.

The third line item is called "Total monetary contributions received this period." It should be a sum of lines 1 and 2 and match what is disclosed on the Form 460's cover sheet on line 1 of column A.

**Comment by gordonje** [comment]
I think this calls for a `Form460ScheduleASummary` model and a `Form460ScheduleASummaryVersion` model with perhaps a base model holding the fields that are common between the two. Might be something we want to add for all of the Form 460 schedules.

**Comment by palewire** [comment]
I believe this is now a draft version of this that will run in the master branch. Needs proofing and perhaps revision but it is in.

**Comment by palewire** [comment]
The Schedule C's are in now too. So the contributions side is mostly done.

**Comment by palewire** [comment]
We still need to add the Schedule E (Expenditures) and other summary sheets. I'm going to try E's soon since it's come up at work.

**Comment by palewire** [comment]
A draft of the Schedule E summaries is in.
