### ISSUE TITLE
Transition to elections models in python-opencivicdata-django

### ISSUE THREAD

**Issue by gordonje** [california-civic-data-coalition/django-calaccess-processed-data#62]
As the implementation of the election models solidify in python-opencivicdata-django, we need to move things around a bit.

- [x] Clean up `calaccess_processed/models/__init__.py`.
- [x] Clean up `calaccess_processed/admins/__init__.py`.
- [x] Move `PartyManager` loading logic to a `loadparties` management command.
- [x] Move `BallotMeasureContestManager` logic to a `loadballotmeasurecontest` management command (some of what we need might be in `ElectionsManager`).
- [x] Move `CandidacyContestManager` logic to a `loadcandidatecontests` management command (some of what we need might be in `ElectionsManager`).
- [x] Create a `loadofficeholders` management command, which will follow from #46.
- [x] Create a `loadretentioncontests` management command from recall-related logic in `ElectionsManager`.
- [x] `git rm calaccess_processed/models/opencivicdata/`
- [x] `git rm calaccess_processed/admins/opencivicdata/`

**Comment by palewire** [comment]
![](https://media0.giphy.com/media/l0EwYnG3qobwxfrSE/giphy.gif)
