### ISSUE TITLE
How we model Recall Elections

### ISSUE THREAD

**Issue by gordonje** [california-civic-data-coalition/django-calaccess-processed-data#63]
According to our OCD election spec, a recall election is modeled as a `RetentionContest` which is a subclass of `BallotMeasureContest`. This is consistent with VIP's schema, and makes a lot of sense because of how these contests come about (through petition gathering initiatives) and how they are presented on the ballot, typically something like "Keep this person in office, yes or no?"

But (at least in California) in addition to that yes/no question, voters are also presented with a slate of candidates from which to choose a successor, should the current officeholder be recalled. For example, here are the results of the [June 2008 State Senate District 12 recall](http://elections.cdn.sos.ca.gov/special-elections/2008-sd12/07_special_election_sov.pdf), which include counts for "yes", "no" and "SIMON SALINAS" (the potential successor).

So under our current schema, in order to fully capture this recall election, we would create a `RetentionContest` _and_ a `CandidateContest` to hold the candidacies of the potential successors. These two contests would be linked to the same `Election` object.

This feels correct to me, on an abstract level, because technically the potential successors are competing against each other, and candidate contest is irrelevant unless the current office holder loses the recall. 

But I can see how some folks might prefer that recall elections be considered a single contest.

Going to stick with the current plan for now and make two contests for every recall. @palewire Let me know if you feel this isn't right or if we need to broaden the discussion.

**Comment by palewire** [comment]
Good point. In my research at work, I've seen similar ballots for recall election in Los Angeles. Here is the final results from the 1950 recall of L.A. Mayor Fletcher Bowron. It also included a slate of candidates below the yes or no question.

![screenshot from 2017-03-23 13-09-25](https://cloud.githubusercontent.com/assets/9993/24268190/0fb30ad4-0fca-11e7-9c4a-14368f53b66f.png)

**Comment by gordonje** [comment]
Nice.

I suppose we could also add a `successor_candidacies` property to `RetentionContest`, but I'm not sure how well that translates to recall elections in other jurisdictions or other kinds of retention contest (e.g., judicial retention contests).
