### ISSUE TITLE
Inserting candidacies not collected by the scrape

### ISSUE THREAD

**Issue by gordonje** [california-civic-data-coalition/django-calaccess-processed-data#69]
Currently, all the records we load into the `Candidacy` model come from scraping. There are, however, other candidacies we can extract from the form 501 filings. These include:
* Candidates running for a known state office who were not "certified" or for whatever reason do not appear on [this web page](http://cal-access.sos.ca.gov/Campaign/Candidates/).
* Candidates for running for a local office, in which case we haven't previously loaded the post or contest.

**Comment by gordonje** [comment]
First step is to isolate the `Form501Filing` objects not currently mapped to a `Candidacy`. This link is stored in `Candidacy.extras` json field with the key `form501filingid`. So we can select this value from the `Candidacy` objects:
```python
Candidacy.objects.filter(extras__has_key='form501filingid').values('extras')
```
And then use the [`in` field lookup](https://docs.djangoproject.com/en/1.11/ref/models/querysets/#in) to exclude `FormF01Filing` objects previously matched to a `Candidacy`:
```python
Form501Filing.objects.exclude(
    form501filing_id__in=[i.extras['form501filingid'] for i in q]
)
```
With my current snapshot of the database, this yields 9,710 unmatched `Form501Filing` objects. That's over 3/4 of all the `Form501Filing` records, which seems like a lot.

**Comment by gordonje** [comment]
Not sure how to use Django's API to get the count of distinct form501 filing_ids from the `Candidacy.extras` json field, but here's the postgres syntax:
```sql
select count(distinct f501.filing_id)
from (
   select extras::json->>'form501filingid' as filing_id
   from opencivicdata_candidacy
) as f501;
```
Which yields 2,793: the exact difference between the count of all `Form501Filing` objects and those that've matched to `Candidacy` objects.

So some of the Form501Filings have matched to multiple Candidacies. Maybe it's the primary and the general election for the same office in the same election cycle?

**Comment by gordonje** [comment]
Anecdotally at least, this does appear to be the case.

Here's one form501 matched to three candidacies:
```python
cands = Candidacy.objects.filter(extras__form501filingid=1455974)
for i in cands:
    print(i, i.election)
```
```
(<Candidacy: NORBY, CHRIS for ASSEMBLY 72 (in 2010 SPECIAL ELECTION)>, <Election: 2010 SPECIAL ELECTION (2010-11-02)>)
(<Candidacy: NORBY, CHRIS for ASSEMBLY 72 (in 2010 SPECIAL RUNOFF)>, <Election: 2010 SPECIAL RUNOFF (2010-08-17)>)
(<Candidacy: NORBY, CHRIS for ASSEMBLY 72 (in 2010 PRIMARY)>, <Election: 2010 PRIMARY (2010-06-08)>)
```

And another matched to two:
```python
cands = Candidacy.objects.filter(extras__form501filingid=1792816)
for i in cands:
    print(i, i.election)
```
```
(<Candidacy: HARPER, MATTHEW for ASSEMBLY 74 (in 2014 GENERAL)>, <Election: 2014 GENERAL (2014-11-04)>)
(<Candidacy: HARPER, MATTHEW for ASSEMBLY 74 (in 2014 PRIMARY)>, <Election: 2014 PRIMARY (2014-06-03)>)
```

**Comment by gordonje** [comment]
Still trying to figure out if there's a problem here.

Seems okay for multiple candidacies to be linked to a single form 501 so long as they're all for the same person, running for the same office in the same election cycle (primary, general and runoff).

So are there any cases where a single form501 filing matched to multiple candidacies of different persons?

```sql
select extras::json->>'form501filingid' as filing_id, count(distinct(person_id))
from opencivicdata_candidacy
where extras::json->>'form501filingid' IS NOT NULL
group by 1
having count(distinct(person_id)) > 1
order by count(distinct(person_id)) desc;
```

Looks like the answer is "yes" 😟

**Comment by gordonje** [comment]
So I checked out the candidacies linked to a few of these filing_ids (1007305, 1007822, 2062011, 1156002) and these are all cases where the scraped candidate's name was not hyperlinked. Hence, no filer_id, hence no person matching.

As further evidence, each pair of dupes shares the same filer_id:
```sql
select 
  extras::json->>'form501filingid' as filing_id, 
  count(distinct c.person_id) as person_id_count,
  count(distinct pid.identifier) as filer_id_count
from opencivicdata_candidacy c
join opencivicdata_personidentifier pid
using (person_id)
where extras::json->>'form501filingid' IS NOT NULL
group by 1
having count(distinct c.person_id ) > 1
order by count(distinct pid.identifier) desc;
```

This should be fixed by merging these `Person` objects, ideally through the OCD api. Or we could wise up `.get_or_create_candidacy()` to look for a candidate with the same name and part in the same cycle, and reuse that person instead of creating a new one.

But we'll leave that task for another day. The current mission is to extract whatever form 501s we can and save them as candidacies.

**Comment by gordonje** [comment]
To pull this off, we'll need to be sure we can link each candidacy in a regular primary to a party.

Currently, we're getting the candidate's party from the `Form501Filing`. However, we can't always find a `Form501Filing` for a scraped candidate and, even when we can, the party field is sometimes blank.

Example: Jeff Perwin ran for State Senate 39 in the 2008 primary and general elections. No hyperlink for ol' Jeff on the CAL-ACCESS web pages, but we're able to dig up form501 with that name, office and primary election. That record has a filer_id (1305083), but no party.

Check out candidate page for this filer_id, though:
<img width="642" alt="perwin" src="https://cloud.githubusercontent.com/assets/4304548/25960482/ad3e3fa6-363c-11e7-9ccf-5eb90b981cf3.png">

So, somehow, CAL-ACCESS knows that this filer_id is a Republican.

**Comment by palewire** [comment]
I think this is done and the ticket can be closed.
