### ISSUE TITLE
Assign Parties to Candidacies with "UNKNOWN PARTY"

### ISSUE THREAD

**Issue by gordonje** [california-civic-data-coalition/django-calaccess-processed-data#71]
Follow up from #70 ...

This matters most for the candidates in the pre-2010 primaries:
```python
q = Candidacy.objects.filter(
    contest__election__start_time__year__lt=2012,
    contest__election__name__contains='PRIMARY'
)

float(q.filter(party__isnull=True).count()) / q.count()
```

Whatever fix we come up with should also included removing the (UNKNOWN PARTY) primaries that currently hold these candidates.

**Comment by palewire** [comment]
I believe this has been done.
