### ISSUE TITLE
Should we archive scraped data as CSVs?

### ISSUE THREAD

**Issue by sahilchinoy** [california-civic-data-coalition/django-calaccess-processed-data#9]
And then insert them into models? Or funnel the data straight into the database?

The former is a bit roundabout, but might be better for tracking purposes -- run the scraper each time we run the process command, for example, and save the resulting CSVs like we do the processed data files.

**Comment by palewire** [comment]
I'm open to different approaches.

Ultimately we will be republishing it as a CSV on our site, but I think we'll also need it in a database table and model so we can link it to other tables as part of our processing routine. 

If you want to shoot straight for the model, I'm fine with that. But don't stress about getting the columns names and whatever perfect on the first pass.

**Comment by sahilchinoy** [comment]
Okay. I think I'll try that, then, so we're not tracking raw, scraped CSVs in the processed data app. The downside to this is that it won't be easy to track how the _raw_ scrapes change -- changes will only be reflected in the final processed data files. If that becomes necessary, we can reevaluate.

**Comment by palewire** [comment]
One thing we could try is caching the raw HTML we scrape. But that's further down the line.

**Comment by gordonje** [comment]
Might be more consistent with our overall design if we make the scraper a separate django app and add it to the requirements of the processed-app. But, yeah, reliably fetching and parsing the markup is the first priority.

**Comment by sahilchinoy** [comment]
Going to proceed with `ScrapedElection` and `ScrapedCandidate` models, and deal with linking them to our existing models derived from 501s later.
